version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    depends_on:
      - mongo
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GIGACHAT_TOKEN=${GIGACHAT_TOKEN}
      - MONGODB_URI=mongodb://mongo:27017

volumes:
  mongo_data:
